name: test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   name: Test
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Test
  #       run: |
  #           bash main.sh test

  sh-checker:
    runs-on: ubuntu-latest
    name: sh-checker
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Run sh-checker
        uses: luizm/action-sh-checker@v0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -d -i 4 -sr
        with:
          sh_checker_comment: true
          sh_checker_exclude: "^deprecation/* ^xiaoyahelper/*"

  ruff:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Ruff
        uses: astral-sh/ruff-action@v3

  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install typing-extensions
          pip install -r aliyuntvtoken_connector/requirements.txt
          pip install -r glue_python/requirements.txt

      - name: Analysing the code with pylint
        run: |
          ROOT=$(pwd)
          pylint --disable=R0801 $(git ls-files '*.py')
